### ISSUE TITLE
Shell is not printed on systems that have there shells in /bin

### ISSUE THREAD

**Issue by jhx0** [rilysh/ansys#1]
Hi @rilysh,

I just played with the code a little.
On my Debian 11 system "Shell:" returns nothing. I can see that the second condition is always hit - running under a tty - which is wrong since i run under X11 currently and i use bash (Which is at /bin/bash).
Maybe it is better to leave out strstr() and just handle the return of getenv() - this would print the full path, which might not be desired. But in this case using a hardcoded sh + 9 (to advance the char pointer) will always result in a empty output on systems that have there shell not under /usr/bin.

```
if (sh != NULL) {
   print("Shell: %s\n", sh); 
} else {
   ...
```

What do you think about that?

PS: I wanted to discuss the issue first before opening a PR.

**Comment by jhx0** [comment]
with the "little patch" i get the correct output on my system

```
OS: Debian GNU/Linux 11 (bullseye)
Host: hp
Arch: x86_64
Kernel: 5.10.0-20-amd64
Shell: /bin/bash
User: x
UID: 1000
Uptime: 09h, 23m, 35s
RAM: 7454 MiB/15789 MiB
Loads: 1.10 1.28 1.68
Brand: GenuineIntel
CPU:  Core(TM) i5-9500 CPU @ 3.00GHz
```

**Comment by jhx0** [comment]
/bin is a symlink to /usr/bin (on Debian).
But since getenv() returns "/bin/bash" it errors out.
The culprit here is the call to getenv().

**Comment by rilysh** [comment]
I think that'd be a better idea. However, there are two ways now left, either just remove "strstr()" or reading `/etc/passwd`, since default shell also listed there according the user.

I'll talk about it in the morning, it's midnight here. Also, thank you for pointing it out!

**Comment by jhx0** [comment]
Yes, the shell is also listed in /etc/passwd. It all depends - the only issue here would be that the current shell used in a terminal emulator for example could differ from the shell given in /etc/passwd (If the user for example spawned the fish shell in a terminal session).

Take your time @rilysh, no need to rush!

**Comment by rilysh** [comment]
Yup, I forgot to mention that as a fallback if the `SHELL` variable is empty or does not exist then it will look up there through UID. https://github.com/rilysh/ansys/blob/321968b6db6e427ae2cbec50cac5131af856c28e/ansys.c#L334

I just pushed some changes (https://github.com/rilysh/ansys/commit/321968b6db6e427ae2cbec50cac5131af856c28e), and the issue should be fixed now :)

**Comment by jhx0** [comment]
Just tried the new code. The issue is gone for me.

```
OS: Debian GNU/Linux 11 (bullseye)
Host: hp
Arch: x86_64
Kernel: 5.10.0-20-amd64
Shell: bash
User: x
UID: 1000
Uptime: 00h, 09m, 20s
RAM: 11452 MiB/15789 MiB
Loads: 1.07 0.89 0.52
Brand: GenuineIntel
CPU:  Core(TM) i5-9500 CPU @ 3.00GHz
```

Will close the issue now since the problem is fixed. ;)

Thanks @rilysh!
